export const API_ENDPOINT = {
  SIGN_IN: "login",
  SIGN_UP: "signup",
  SIGN_OUT: "logout",
  LOGININFO_ROLE_UPDATE: "loginInfo/updateRole",
  REFRESH_TOKEN: "auth/refresh",
  USER: "users",
  USER_STATUS: "users/toggleStatus",
  USERS_WITH_LOGIN_INFO: "users/withLoginInfo",
  USER_PROFILE: "userProfiles",
  USER_PROFILE_PER_USER : "userProfiles/user",
  PROFILE: "profiles",
  TASKS: "tasks",
  USET_TASKS: "tasks/userId",
  FREELANCERS: "search/loadAllFreelancersByFilter",
  TASK_STATUS: "tasks/toggleStatus",
  TASK: "tasks",
};
