export const API_ENDPOINT = {
  SIGN_IN: "login",
  SIGN_UP: "signup",
  SIGN_OUT: "logout",
  LOGININFO_ROLE_UPDATE: "loginInfo/updateRole",
  REFRESH_TOKEN: "auth/refresh",
  USER: "users",
  USER_STATUS: "users/toggleStatus",
  USERS_WITH_LOGIN_INFO: "users/withLoginInfo",
  USER_PROFILE: "userProfiles",
  USER_PROFILE_PER_USER : "userProfiles/user",
  PROFILE: "profiles",
  TASKS: "tasks",
  USET_TASKS: "tasks/userId",
  FREELANCERS: "search/loadAllFreelancersByFilter",
  FREELANCER_TIMES: "freelancerTimeSlots/freelancer",
  TASK_STATUS: "tasks/toggleStatus",
  COMMENTS: "comments",
  COMMENTS_TASK: "comments/task",
  TIME_SLOTS: "/freelancerTimeSlots",
  TASK_OFFER : "taskOffereds",
  BOOKING_SLOTS : "bookingSlots",
  BOOKING_SLOTS_BUYER : "bookingSlots/buyer",
  BOOKING_SLOTS_USER : "bookingSlots/user",
  PAST_BOOKINGS : "bookingSlots/user/past",
  UPCOMING_BOOKINGS : "bookingSlots/user/future",
  PAST_BOOKINGS_BY_BUYER : "bookingSlots/buyer/past",
  UPCOMING_BOOKINGS_BY_BUYER : "bookingSlots/buyer/future",

};
