export const API_ENDPOINT = {
  SIGN_IN: "login",
  SIGN_UP: "signup",
  SIGN_OUT: "logout",
  LOGININFO_ROLE_UPDATE: "loginInfo/updateRole",
  REFRESH_TOKEN: "auth/refresh",
  USER: "users",
  USER_STATUS: "users/toggleStatus",
  USERS_WITH_LOGIN_INFO: "users/withLoginInfo",
  USER_PROFILE: "userProfiles",
  USER_PROFILE_PER_USER : "userProfiles/user",
  PROFILE: "profiles",
  PROFILE_ALL: "profiles/all",
  PROFILE_STATUS: "profiles/toggleStatus",
  TASKS: "tasks",
  TASK_ALL:"tasks/all",
  USET_TASKS: "tasks/userId",
  FREELANCERS: "search/loadAllFreelancersByFilter",
  FREELANCER_TIMES: "freelancerTimeSlots/freelancer",
  TASK_STATUS: "tasks/toggleStatus",
  COMMENTS: "comments",
  COMMENTS_TASK: "comments/task",
  TIME_SLOTS: "/freelancerTimeSlots",
  TASK_OFFER : "taskOffereds",
  BOOKING_SLOTS : "bookingSlots",
  BOOKING_SLOTS_STATUS : "bookingSlots/toggleStatus",
  BOOKING_SLOT_USER:"bookingSlotsWithUser",
  BOOKING_SLOTS_BUYER : "bookingSlots/buyer",
  BOOKING_SLOTS_USER : "bookingSlots/user",
  PAST_BOOKINGS : "bookingSlots/user/past",
  UPCOMING_BOOKINGS : "bookingSlots/user/future",
  PAST_BOOKINGS_BY_BUYER : "bookingSlots/buyer/past",
  UPCOMING_BOOKINGS_BY_BUYER : "bookingSlots/buyer/future",
  RATINGS : "ratings",
  RATINGS_BY_FREELANCER : "/ratings/buyer",
  TASKS_OFFERED : "/taskOffereds/offerUser",
  TASKS_CREATED : "/taskOffereds/createdUser",
  LOCATIONS: "locations",
  NOTIFICATION: "notifications/user",
  NOTIFICATION_READ: "notifications",
  CACHE:"redis/cache"
};
