export const Routes = {
  HOME: "/",
  SIGNIN: "/sign-in",
  SIGNUP: "/sign-up",
  PROFILE: "/profile",
  FREELANCER: "/freelancer",
  PROFILES: "/freelancer/profiles",
  BUYER: "/buyer",
  ADMIN: "/admin",
  FREELANCER_DETAILS: "/buyer/freelancer/:id",
  USER_SETTINGS: "/settings/:id",
  TASK_MANAGEMENT: "/task",
  TASK_DETAIL: "/task/:id",
  CALENDAR: "/calendar",
  COMPLTED_BOOKINGS: "/bookings/completed",
  UPCOMING_BOOKINGS: "/bookings/upcoming",
  TASK_OFFERED: "/task/offered",
  SERVICES: "/services",
  ABOUT: "/about-us",

};
